import logging
import os
import smtplib
from datetime import datetime, timedelta, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from jinja2 import Environment, FileSystemLoader

from config import (
    ARXIV_CATEGORIES,
    EMAIL_FROM,
    EMAIL_TO,
    SMTP_PASSWORD,
    SMTP_PORT,
    SMTP_SERVER,
    SMTP_USERNAME,
)

logger = logging.getLogger(__name__)


def _generate_plain_text(papers: list[dict]) -> str:
    """Generate plain text fallback for email clients that don't render HTML."""
    now = datetime.now(tz=timezone.utc)
    start = (now - timedelta(days=7)).strftime("%Y-%m-%d")
    end = now.strftime("%Y-%m-%d")

    lines = [
        f"Weekly AI Papers Digest / 每周 AI 论文精选",
        f"{start} ~ {end} | 共 {len(papers)} 篇论文",
        "=" * 60,
        "",
    ]

    for i, paper in enumerate(papers, 1):
        authors = ", ".join(paper["authors"][:3])
        if len(paper["authors"]) > 3:
            authors += " et al."
        summary = paper.get("summary", {})

        lines.extend(
            [
                f"#{i} [{paper['importance_score']}/10] {paper['title']}",
                f"   Authors: {authors}",
                f"   Categories: {', '.join(paper['categories'])}",
                f"   PDF: {paper['pdf_url']}",
                "",
                f"   问题 Problem: {summary.get('problem', 'N/A')}",
                f"   解决方案 Solution: {summary.get('solution', 'N/A')}",
                f"   创新之处 Innovation: {summary.get('innovation', 'N/A')}",
                "",
                "-" * 60,
                "",
            ]
        )

    lines.append("Generated by Weekly Papers Digest | Powered by arXiv API + Kimi")
    return "\n".join(lines)


def send_digest(papers: list[dict]) -> None:
    """Compose and send the weekly digest email."""
    now = datetime.now(tz=timezone.utc)
    start = (now - timedelta(days=7)).strftime("%Y-%m-%d")
    end = now.strftime("%Y-%m-%d")
    date_range = f"{start} ~ {end}"

    # Render HTML template
    template_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates")
    env = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template("digest_email.html")

    html_content = template.render(
        papers=papers,
        date_range=date_range,
        paper_count=len(papers),
        categories=ARXIV_CATEGORIES,
    )

    plain_text = _generate_plain_text(papers)

    # Compose email
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Weekly AI Papers Digest | 每周AI论文精选 ({end})"
    msg["From"] = EMAIL_FROM
    msg["To"] = EMAIL_TO

    msg.attach(MIMEText(plain_text, "plain", "utf-8"))
    msg.attach(MIMEText(html_content, "html", "utf-8"))

    # Send
    recipients = [addr.strip() for addr in EMAIL_TO.split(",")]
    logger.info(f"Sending digest email to {recipients}...")

    with smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT) as server:
        server.login(SMTP_USERNAME, SMTP_PASSWORD)
        server.sendmail(EMAIL_FROM, recipients, msg.as_string())

    logger.info("Digest email sent successfully")
